@baseurl = http://localhost:3000/parkingSpots

###

POST {{baseurl}}/ HTTP/1.1
content-type: application/json

{
    "latitude": 76.0999123,
    "longitude": 88.03131,
    "handicapped": false,
    "presence": false
}

### 
GET {{baseurl}}/ HTTP/1.1

###

DELETE {{baseurl}}/5dfb58a1b8595c563d457c80 HTTP/1.1

###

PUT {{baseurl}}/5dfb78bd953f956f44cc51c8 HTTP/1.1
content-type: application/json

{
    "latitude": 91.11313111
}

###
PUT {{baseurl}}/5dfba5d6d2e371302b98d1e6/hourlyPrice HTTP/1.1
content-type: application/json

{
    "hourlyPrice": 12
}

###

GET {{baseurl}}/nearest HTTP/1.1
content-type: application/json

{
    "latitude": 75.0,
    "longitude": 40.0
}

###
PUT {{baseurl}}/5dfb78ad953f956f44cc51c8/presence HTTP/1.1
content-type: application/json

{
    "presence": true
}