@baseurl = http://localhost:3000/users

###

POST {{baseurl}}/ HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "User",
    "email": "testuser@example.com",
    "username": "test.user",
    "password": "testpassword"
}

### 
GET {{baseurl}}/ HTTP/1.1

###

DELETE {{baseurl}}/ HTTP/1.1

###

PUT {{baseurl}}/ HTTP/1.1
content-type: application/json

{
    "username":"corrado.petrelli",
    "balance": 200,
    "password": "newpass"
}