@baseurl = http://localhost:3000

###

POST {{baseurl}}/users HTTP/1.1
content-type: application/json

{
    "firstName": "Corrado",
    "lastName": "Petrelli",
    "username": "corrado.petrelli",
    "password": "aldoaldoaldo"
}

### 
GET {{baseurl}}/users HTTP/1.1

###

DELETE {{baseurl}}/users HTTP/1.1

###

PUT {{baseurl}}/users HTTP/1.1
content-type: application/json

{
    "username":"corrado.petrelli",
    "balance": 200,
    "password": "newpass"
}